### ISSUE TITLE
mediawiki + full text search 설치 문의

### ISSUE THREAD

**Issue by woojuri** [pinedance/pinedance.github.io#6]
선생님의 사이트를 보고
mediawiki에 full text search 기능을 설치하려고
Elasticsearch와 Cirrussearch 등을 설치하려다가 에러를 만나 한 달째 처리를 못해
도움을 요청합니다. 

bitnami에서 제공하는 mediawiki를 설치하고
Elasticsearch를 설치하여 정상 작동하는 것까지는 확인했습니다. 

그런데 
인덱스 만들기 위한 config 만들기 등을 하라고 하는데, 첫번째 config부터 안 되네요. 
(첫번째 단계인 updateSearchIndexConfig.php를 실행하니 에러가 생기네요)

에러로그 남기도록 설정하는 것을 알게 되어 기록을 보니
---
[SQLBagOStuff] MainObjectStash using store ReplicatedBagOStuff
[objectcache] MainWANObjectCache using store EmptyBagOStuff
IP: 127.0.0.1
Start command line script /opt/bitnami/apps/mediawiki/htdocs/extensions/CirrusSearch/maintenance/updateSearchIndexConfig.php
[localisation] LocalisationCache: using store LCStoreDB
[DBQuery] Wikimedia\Rdbms\DatabaseMysqlBase::open [0s] localhost:3306: SET group_concat_max_len = 262144, sql_mode = ''
[DBReplication] Wikimedia\Rdbms\LBFactory::getChronologyProtector: request info {
    "IPAddress": "127.0.0.1",
    "UserAgent": false,
    "ChronologyProtection": false,
    "ChronologyPositionIndex": 0,
    "ChronologyClientId": false
}
[DBConnection] Wikimedia\Rdbms\LoadBalancer::lazyLoadReplicationPositions: executed chronology callback.
[DBConnection] Wikimedia\Rdbms\LoadBalancer::getLocalConnection: connected to database 0 at 'localhost:3306'.
[DBQuery] Wikimedia\Rdbms\DatabaseMysqlBase::serverIsReadOnly [0s] localhost:3306: SELECT @@GLOBAL.read_only AS Value
[DBQuery] LCStoreDB::get [0s] localhost:3306: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'ko' AND lc_key = 'deps'  LIMIT 1  
[DBQuery] LCStoreDB::get [0.001s] localhost:3306: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'ko' AND lc_key = 'list'  LIMIT 1  
[DBQuery] LCStoreDB::get [0s] localhost:3306: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'ko' AND lc_key = 'preload'  LIMIT 1  
[DBQuery] LCStoreDB::get [0s] localhost:3306: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'ko' AND lc_key = 'preload'  LIMIT 1  
[DBQuery] LCStoreDB::get [0s] localhost:3306: SELECT  lc_value  FROM `l10n_cache`    WHERE lc_lang = 'ko' AND lc_key = 'fallbackSequence'  LIMIT 1  
[session] SessionManager using store SqlBagOStuff
[exception] [a4076080ea9050522cdc898d] [no req]   Error from line 109 of /opt/bitnami/apps/mediawiki/htdocs/extensions/CirrusSearch/includes/Maintenance/Maintenance.php: Class 'CirrusSearch\Connection' not found
#0 /opt/bitnami/apps/mediawiki/htdocs/extensions/CirrusSearch/maintenance/updateSearchIndexConfig.php(54): CirrusSearch\Maintenance\Maintenance->getConnection()
#1 /opt/bitnami/apps/mediawiki/htdocs/maintenance/doMaintenance.php(99): CirrusSearch\Maintenance\UpdateSearchIndexConfig->execute()
#2 /opt/bitnami/apps/mediawiki/htdocs/extensions/CirrusSearch/maintenance/updateSearchIndexConfig.php(65): require_once(string)
#3 {main}
[DBConnection] Wikimedia\Rdbms\LBFactory::destroy: closing connection to database 'localhost:3306'.
---
라고 나오네요. 
문제는 로그파일이 무슨 뜻인지 모르겠습니다. ㅜㅜ

혹시 인텍싱 단계에서 왜 문제가 생기는지 가르쳐주실 수 있나요?

고맙습니다.

**Comment by pinedance** [comment]
확인이 늦었습니다. [MediaWiki에서 Full text 검색](https://github.com/pinedance/pinedance.github.io/issues/6)이라는 글을 보고 문의하신 듯합니다. 

저도 셋팅을 한 이후로 관심을 갖지 않아서 깊이 알지는 못합니다만 아래 부분이 문제인 것 같네요. 

```
Error from line 109 of /opt/bitnami/apps/mediawiki/htdocs/extensions/CirrusSearch/includes/Maintenance/Maintenance.php: Class 'CirrusSearch\Connection' not found
```

이것만 보면 `CirrusSearch\Connection` class를 찾을 수 없다는 말이니  설치가 올바르게 되지 않았거나 버전이 맞지 않는 문제를 생각해 볼 수 있을 것 같습니다. 

다음 사항을 다시 한 번 점검해 보시면 어떨까요

* 버전 문제
	* [mediawiki와 elaticsearch 버전 문제](https://www.mediawiki.org/wiki/Extension:CirrusSearch#Elasticsearch)
	* [mediawiki와 Elastica 버전 문제](https://www.mediawiki.org/wiki/Special:ExtensionDistributor/Elastica)
	* [mediawiki와 CirrusSearch 버전문제](https://www.mediawiki.org/wiki/Special:ExtensionDistributor/CirrusSearch)

* 설치 문제
	* mediawiki `Special:Version`에서 설치 여부 확인
	* [Elastica 다운로드 후 composer 실행 여부](https://www.mediawiki.org/wiki/Extension:CirrusSearch#Elastica)
	* [CirrusSeach 준비 확인](https://phabricator.wikimedia.org/source/extension-cirrussearch/browse/master/README)
	
좋은 결과 있으시기 바랍니다.
